### PR TITLE
rewrite entire crate to run on bytes

### PR DESCRIPTION
**Pull request by untitaker**
as per #12, change everything to run on bytes. Statemachine transitions are now per-byte, character boundaries are validated in emitter.

Open questions:

- [x] do we want to allow reading from raw bytes? currently BufReadReader does not validate any input, leading to panics in emitter when converting to string
- [x] where do we validate the characters of the input stream? maybe we want to do that in the emitter now, when assembling tokens? -- terrible idea, breaks tests in irreparable ways
- [x] serious performance regression with hyperlink
- [x] surrogate detection possible? seems too hard after initial attempt -- let's not
- [x] fuzzing in comparison mode
- [x] separate fuzzing testcases from rest
- [x] change fuzzing code such that it fuzzes arbitrary bytes
- [x] fuzz against crashes

### CODE REVIEW

**Comment by untitaker** [comment]
Remaining concern: Errors are now per-byte. This causes issues because invalid characters are now reported before they're fully consumed. See testcase in ee22d8d which passes in an earlier version of html5gum.

**Comment by untitaker** [comment]
@ygg01 i'm close to merging this, i'm waiting for fuzzer results atm. performance gains are visible but not significant imo. Is there anything that catches your eye?

**Comment by Ygg01** [comment]
@untitaker not too obvious, one thing in future that might help is just converting fields from `String` ->  `Vec<u8>` that way `quick-xml` does and it might be better for working with custom encodings. That said, I could take a crack at it, once the Holidays pass. Just don't hold your breath.

**Comment by untitaker** [comment]
>one thing in future that might help is just converting fields from String -> Vec<u8> that way quick-xml does

wdym? something better than `into_bytes()`?

**Comment by untitaker** [comment]
oh. you mean changing the typedef. i think most should be Vec<u8> already in this PR, did I miss something?

**Pull request merged**
